[package]
name = "lain-app"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
bevy = "0.15.1"
bevy_vrm = "0.0.12"
gltf = { version = "1.4.1", features = ["import"] }
bytemuck = "1.21.0"
pollster = "0.4.0"
